apiVersion: batch/v1
kind: CronJob
metadata:
  name: engineering-training-2023-batch
spec:
  startingDeadlineSeconds: 60
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: engineering-training-2023-batch
          restartPolicy: OnFailure
          containers:
            - name: engineering-training-2023-batch
              env:
                - name: AWS_DEFAULT_REGION
                  value: ap-northeast-1
              resources:
                requests:
                  cpu: 100m
                  memory:
                    512Mi
                limits:
                  memory: 512Mi
