apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-training-2023-app
spec:
  selector:
    matchLabels:
      app: engineering-training-2023-app
  template:
    metadata:
      labels:
        app: engineering-training-2023-app
        securityGroupPolicy: engineering-training-2023
        infrastructure: fargate
    spec:
      containers:
        - name: engineering-training-2023-app
          env:
            - name: STREAMLIT_SERVER_BASE_URL_PATH
              value: apps
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-1
            - name: BACKEND_HOST
              value: http://engineering-training-2023-api:8000
          resources:
            requests:
              cpu: 100m
              memory:
                512Mi
            limits:
              memory: 512Mi
