apiVersion: v1
kind: Service
metadata:
  name: engineering-training-2023-app
spec:
  selector:
    app: engineering-training-2023-app
  ports:
    - name: http
      port: 8081
      targetPort: 8080
