apiVersion: v1
kind: Service
metadata:
  name: engineering-training-2023-api
spec:
  selector:
    app: engineering-training-2023-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
