apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-training-2023-app
spec:
  template:
    spec:
      containers:
        - name: engineering-training-2023-app
          image: "" # イメージを指定
