[global]
developmentMode = false
dataFrameSerialization = "legacy"

[server]
port = 8080
runOnSave = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = false
caching = false

[ui]
hideTopBar = true

[theme]
base="light"
primaryColor="#004E98"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8F9FA"
textColor="#002060"
